/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MedicalRecord = IDL.Record({
  'id' : IDL.Text,
  'patientId' : IDL.Text,
  'fileName' : IDL.Text,
  'fileType' : IDL.Text,
  'appointmentId' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'patientId' : IDL.Text,
  'clinicId' : IDL.Text,
  'date' : IDL.Text,
  'comment' : IDL.Text,
  'patientName' : IDL.Text,
  'rating' : IDL.Nat,
});
export const Appointment = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'doctorId' : IDL.Text,
  'couponCode' : IDL.Text,
  'paymentStatus' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'patientId' : IDL.Text,
  'clinicId' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'queuePosition' : IDL.Nat,
  'suggestedDate' : IDL.Text,
  'suggestedTime' : IDL.Text,
  'discount' : IDL.Nat,
  'amount' : IDL.Nat,
  'departmentId' : IDL.Text,
  'timeWindow' : IDL.Text,
  'reason' : IDL.Text,
});
export const Coupon = IDL.Record({
  'id' : IDL.Text,
  'discountValue' : IDL.Nat,
  'expiryDate' : IDL.Text,
  'clinicId' : IDL.Text,
  'code' : IDL.Text,
  'discountType' : IDL.Text,
  'usedCount' : IDL.Nat,
  'isActive' : IDL.Bool,
  'maxUses' : IDL.Nat,
});
export const Doctor = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'isTodayAvailable' : IDL.Bool,
  'clinicId' : IDL.Text,
  'name' : IDL.Text,
  'photoUrl' : IDL.Text,
  'qualifications' : IDL.Text,
  'experience' : IDL.Nat,
  'availableDays' : IDL.Vec(IDL.Text),
  'specialization' : IDL.Text,
  'consultationFee' : IDL.Nat,
  'departmentId' : IDL.Text,
});
export const Patient = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'gender' : IDL.Text,
  'phone' : IDL.Text,
});
export const Payment = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'method' : IDL.Text,
  'patientId' : IDL.Text,
  'createdAt' : IDL.Int,
  'amount' : IDL.Nat,
  'appointmentId' : IDL.Text,
});
export const Clinic = IDL.Record({
  'id' : IDL.Text,
  'tagline' : IDL.Text,
  'city' : IDL.Text,
  'primaryColor' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'accentColor' : IDL.Text,
  'workingHours' : IDL.Text,
  'address' : IDL.Text,
  'upiId' : IDL.Text,
  'phone' : IDL.Text,
});
export const Department = IDL.Record({
  'id' : IDL.Text,
  'clinicId' : IDL.Text,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMedicalRecord' : IDL.Func([MedicalRecord], [IDL.Text], []),
  'addReview' : IDL.Func([Review], [IDL.Text], []),
  'createAppointment' : IDL.Func([Appointment], [IDL.Text], []),
  'createCoupon' : IDL.Func([Coupon], [IDL.Text], []),
  'createDoctor' : IDL.Func([Doctor], [IDL.Text], []),
  'createPatient' : IDL.Func([Patient], [IDL.Text], []),
  'createPayment' : IDL.Func([Payment], [IDL.Text], []),
  'deleteDoctor' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAppointmentsByDoctor' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getAppointmentsByPatient' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getClinicInfo' : IDL.Func([], [IDL.Opt(Clinic)], ['query']),
  'getCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'getDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
  'getDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getDoctorsByDepartment' : IDL.Func([IDL.Text], [IDL.Vec(Doctor)], ['query']),
  'getMedicalRecords' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MedicalRecord)],
      ['query'],
    ),
  'getPatient' : IDL.Func([IDL.Text], [IDL.Opt(Patient)], ['query']),
  'getPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getTodayAppointments' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'updateAppointmentStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateClinicInfo' : IDL.Func([Clinic], [IDL.Bool], []),
  'updateCoupon' : IDL.Func([Coupon], [IDL.Bool], []),
  'updateDoctor' : IDL.Func([Doctor], [IDL.Bool], []),
  'updatePatient' : IDL.Func([Patient], [IDL.Bool], []),
  'updatePaymentStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'validateCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MedicalRecord = IDL.Record({
    'id' : IDL.Text,
    'patientId' : IDL.Text,
    'fileName' : IDL.Text,
    'fileType' : IDL.Text,
    'appointmentId' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'patientId' : IDL.Text,
    'clinicId' : IDL.Text,
    'date' : IDL.Text,
    'comment' : IDL.Text,
    'patientName' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'doctorId' : IDL.Text,
    'couponCode' : IDL.Text,
    'paymentStatus' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'patientId' : IDL.Text,
    'clinicId' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'queuePosition' : IDL.Nat,
    'suggestedDate' : IDL.Text,
    'suggestedTime' : IDL.Text,
    'discount' : IDL.Nat,
    'amount' : IDL.Nat,
    'departmentId' : IDL.Text,
    'timeWindow' : IDL.Text,
    'reason' : IDL.Text,
  });
  const Coupon = IDL.Record({
    'id' : IDL.Text,
    'discountValue' : IDL.Nat,
    'expiryDate' : IDL.Text,
    'clinicId' : IDL.Text,
    'code' : IDL.Text,
    'discountType' : IDL.Text,
    'usedCount' : IDL.Nat,
    'isActive' : IDL.Bool,
    'maxUses' : IDL.Nat,
  });
  const Doctor = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'isTodayAvailable' : IDL.Bool,
    'clinicId' : IDL.Text,
    'name' : IDL.Text,
    'photoUrl' : IDL.Text,
    'qualifications' : IDL.Text,
    'experience' : IDL.Nat,
    'availableDays' : IDL.Vec(IDL.Text),
    'specialization' : IDL.Text,
    'consultationFee' : IDL.Nat,
    'departmentId' : IDL.Text,
  });
  const Patient = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'gender' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Payment = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'method' : IDL.Text,
    'patientId' : IDL.Text,
    'createdAt' : IDL.Int,
    'amount' : IDL.Nat,
    'appointmentId' : IDL.Text,
  });
  const Clinic = IDL.Record({
    'id' : IDL.Text,
    'tagline' : IDL.Text,
    'city' : IDL.Text,
    'primaryColor' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'accentColor' : IDL.Text,
    'workingHours' : IDL.Text,
    'address' : IDL.Text,
    'upiId' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Department = IDL.Record({
    'id' : IDL.Text,
    'clinicId' : IDL.Text,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'addMedicalRecord' : IDL.Func([MedicalRecord], [IDL.Text], []),
    'addReview' : IDL.Func([Review], [IDL.Text], []),
    'createAppointment' : IDL.Func([Appointment], [IDL.Text], []),
    'createCoupon' : IDL.Func([Coupon], [IDL.Text], []),
    'createDoctor' : IDL.Func([Doctor], [IDL.Text], []),
    'createPatient' : IDL.Func([Patient], [IDL.Text], []),
    'createPayment' : IDL.Func([Payment], [IDL.Text], []),
    'deleteDoctor' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAppointmentsByDoctor' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getAppointmentsByPatient' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getClinicInfo' : IDL.Func([], [IDL.Opt(Clinic)], ['query']),
    'getCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'getDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
    'getDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getDoctorsByDepartment' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Doctor)],
        ['query'],
      ),
    'getMedicalRecords' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MedicalRecord)],
        ['query'],
      ),
    'getPatient' : IDL.Func([IDL.Text], [IDL.Opt(Patient)], ['query']),
    'getPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getTodayAppointments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'updateAppointmentStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateClinicInfo' : IDL.Func([Clinic], [IDL.Bool], []),
    'updateCoupon' : IDL.Func([Coupon], [IDL.Bool], []),
    'updateDoctor' : IDL.Func([Doctor], [IDL.Bool], []),
    'updatePatient' : IDL.Func([Patient], [IDL.Bool], []),
    'updatePaymentStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'validateCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };