/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : string,
  'status' : string,
  'doctorId' : string,
  'couponCode' : string,
  'paymentStatus' : string,
  'paymentMethod' : string,
  'patientId' : string,
  'clinicId' : string,
  'date' : string,
  'createdAt' : bigint,
  'queuePosition' : bigint,
  'suggestedDate' : string,
  'suggestedTime' : string,
  'discount' : bigint,
  'amount' : bigint,
  'departmentId' : string,
  'timeWindow' : string,
  'reason' : string,
}
export interface Clinic {
  'id' : string,
  'tagline' : string,
  'city' : string,
  'primaryColor' : string,
  'name' : string,
  'email' : string,
  'website' : string,
  'accentColor' : string,
  'workingHours' : string,
  'address' : string,
  'upiId' : string,
  'phone' : string,
}
export interface Coupon {
  'id' : string,
  'discountValue' : bigint,
  'expiryDate' : string,
  'clinicId' : string,
  'code' : string,
  'discountType' : string,
  'usedCount' : bigint,
  'isActive' : boolean,
  'maxUses' : bigint,
}
export interface Department {
  'id' : string,
  'clinicId' : string,
  'icon' : string,
  'name' : string,
  'description' : string,
}
export interface Doctor {
  'id' : string,
  'bio' : string,
  'isTodayAvailable' : boolean,
  'clinicId' : string,
  'name' : string,
  'photoUrl' : string,
  'qualifications' : string,
  'experience' : bigint,
  'availableDays' : Array<string>,
  'specialization' : string,
  'consultationFee' : bigint,
  'departmentId' : string,
}
export interface MedicalRecord {
  'id' : string,
  'patientId' : string,
  'fileName' : string,
  'fileType' : string,
  'appointmentId' : string,
  'uploadedAt' : bigint,
}
export interface Patient {
  'id' : string,
  'age' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'address' : string,
  'gender' : string,
  'phone' : string,
}
export interface Payment {
  'id' : string,
  'status' : string,
  'method' : string,
  'patientId' : string,
  'createdAt' : bigint,
  'amount' : bigint,
  'appointmentId' : string,
}
export interface Review {
  'id' : string,
  'patientId' : string,
  'clinicId' : string,
  'date' : string,
  'comment' : string,
  'patientName' : string,
  'rating' : bigint,
}
export interface _SERVICE {
  'addMedicalRecord' : ActorMethod<[MedicalRecord], string>,
  'addReview' : ActorMethod<[Review], string>,
  'createAppointment' : ActorMethod<[Appointment], string>,
  'createCoupon' : ActorMethod<[Coupon], string>,
  'createDoctor' : ActorMethod<[Doctor], string>,
  'createPatient' : ActorMethod<[Patient], string>,
  'createPayment' : ActorMethod<[Payment], string>,
  'deleteDoctor' : ActorMethod<[string], boolean>,
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAppointmentsByDoctor' : ActorMethod<[string], Array<Appointment>>,
  'getAppointmentsByPatient' : ActorMethod<[string], Array<Appointment>>,
  'getClinicInfo' : ActorMethod<[], [] | [Clinic]>,
  'getCoupons' : ActorMethod<[], Array<Coupon>>,
  'getDepartments' : ActorMethod<[], Array<Department>>,
  'getDoctors' : ActorMethod<[], Array<Doctor>>,
  'getDoctorsByDepartment' : ActorMethod<[string], Array<Doctor>>,
  'getMedicalRecords' : ActorMethod<[string], Array<MedicalRecord>>,
  'getPatient' : ActorMethod<[string], [] | [Patient]>,
  'getPatients' : ActorMethod<[], Array<Patient>>,
  'getPayments' : ActorMethod<[], Array<Payment>>,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'getTodayAppointments' : ActorMethod<[string], Array<Appointment>>,
  'updateAppointmentStatus' : ActorMethod<
    [string, string, string, string],
    boolean
  >,
  'updateClinicInfo' : ActorMethod<[Clinic], boolean>,
  'updateCoupon' : ActorMethod<[Coupon], boolean>,
  'updateDoctor' : ActorMethod<[Doctor], boolean>,
  'updatePatient' : ActorMethod<[Patient], boolean>,
  'updatePaymentStatus' : ActorMethod<[string, string], boolean>,
  'validateCoupon' : ActorMethod<[string], [] | [Coupon]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];