/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MedicalRecord {
    id: string;
    patientId: string;
    fileName: string;
    fileType: string;
    appointmentId: string;
    uploadedAt: bigint;
}
export interface Department {
    id: string;
    clinicId: string;
    icon: string;
    name: string;
    description: string;
}
export interface Clinic {
    id: string;
    tagline: string;
    city: string;
    primaryColor: string;
    name: string;
    email: string;
    website: string;
    accentColor: string;
    workingHours: string;
    address: string;
    upiId: string;
    phone: string;
}
export interface Coupon {
    id: string;
    discountValue: bigint;
    expiryDate: string;
    clinicId: string;
    code: string;
    discountType: string;
    usedCount: bigint;
    isActive: boolean;
    maxUses: bigint;
}
export interface Doctor {
    id: string;
    bio: string;
    isTodayAvailable: boolean;
    clinicId: string;
    name: string;
    photoUrl: string;
    qualifications: string;
    experience: bigint;
    availableDays: Array<string>;
    specialization: string;
    consultationFee: bigint;
    departmentId: string;
}
export interface Payment {
    id: string;
    status: string;
    method: string;
    patientId: string;
    createdAt: bigint;
    amount: bigint;
    appointmentId: string;
}
export interface Appointment {
    id: string;
    status: string;
    doctorId: string;
    couponCode: string;
    paymentStatus: string;
    paymentMethod: string;
    patientId: string;
    clinicId: string;
    date: string;
    createdAt: bigint;
    queuePosition: bigint;
    suggestedDate: string;
    suggestedTime: string;
    discount: bigint;
    amount: bigint;
    departmentId: string;
    timeWindow: string;
    reason: string;
}
export interface Patient {
    id: string;
    age: bigint;
    name: string;
    createdAt: bigint;
    email: string;
    address: string;
    gender: string;
    phone: string;
}
export interface Review {
    id: string;
    patientId: string;
    clinicId: string;
    date: string;
    comment: string;
    patientName: string;
    rating: bigint;
}
export interface backendInterface {
    addMedicalRecord(record: MedicalRecord): Promise<string>;
    addReview(review: Review): Promise<string>;
    createAppointment(appointment: Appointment): Promise<string>;
    createCoupon(coupon: Coupon): Promise<string>;
    createDoctor(doctor: Doctor): Promise<string>;
    createPatient(patient: Patient): Promise<string>;
    createPayment(payment: Payment): Promise<string>;
    deleteDoctor(id: string): Promise<boolean>;
    getAppointments(): Promise<Array<Appointment>>;
    getAppointmentsByDoctor(doctorId: string): Promise<Array<Appointment>>;
    getAppointmentsByPatient(patientId: string): Promise<Array<Appointment>>;
    getClinicInfo(): Promise<Clinic | null>;
    getCoupons(): Promise<Array<Coupon>>;
    getDepartments(): Promise<Array<Department>>;
    getDoctors(): Promise<Array<Doctor>>;
    getDoctorsByDepartment(departmentId: string): Promise<Array<Doctor>>;
    getMedicalRecords(patientId: string): Promise<Array<MedicalRecord>>;
    getPatient(patientId: string): Promise<Patient | null>;
    getPatients(): Promise<Array<Patient>>;
    getPayments(): Promise<Array<Payment>>;
    getReviews(): Promise<Array<Review>>;
    getTodayAppointments(date: string): Promise<Array<Appointment>>;
    updateAppointmentStatus(id: string, status: string, suggestedDate: string, suggestedTime: string): Promise<boolean>;
    updateClinicInfo(clinic: Clinic): Promise<boolean>;
    updateCoupon(coupon: Coupon): Promise<boolean>;
    updateDoctor(doctor: Doctor): Promise<boolean>;
    updatePatient(patient: Patient): Promise<boolean>;
    updatePaymentStatus(id: string, status: string): Promise<boolean>;
    validateCoupon(code: string): Promise<Coupon | null>;
}
import type { Clinic as _Clinic, Coupon as _Coupon, Patient as _Patient } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMedicalRecord(arg0: MedicalRecord): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedicalRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedicalRecord(arg0);
            return result;
        }
    }
    async addReview(arg0: Review): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0);
            return result;
        }
    }
    async createAppointment(arg0: Appointment): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppointment(arg0);
            return result;
        }
    }
    async createCoupon(arg0: Coupon): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCoupon(arg0);
            return result;
        }
    }
    async createDoctor(arg0: Doctor): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDoctor(arg0);
            return result;
        }
    }
    async createPatient(arg0: Patient): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPatient(arg0);
            return result;
        }
    }
    async createPayment(arg0: Payment): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayment(arg0);
            return result;
        }
    }
    async deleteDoctor(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDoctor(arg0);
            return result;
        }
    }
    async getAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointments();
            return result;
        }
    }
    async getAppointmentsByDoctor(arg0: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByDoctor(arg0);
            return result;
        }
    }
    async getAppointmentsByPatient(arg0: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByPatient(arg0);
            return result;
        }
    }
    async getClinicInfo(): Promise<Clinic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClinicInfo();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClinicInfo();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoupons(): Promise<Array<Coupon>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoupons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoupons();
            return result;
        }
    }
    async getDepartments(): Promise<Array<Department>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepartments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepartments();
            return result;
        }
    }
    async getDoctors(): Promise<Array<Doctor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctors();
            return result;
        }
    }
    async getDoctorsByDepartment(arg0: string): Promise<Array<Doctor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctorsByDepartment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctorsByDepartment(arg0);
            return result;
        }
    }
    async getMedicalRecords(arg0: string): Promise<Array<MedicalRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicalRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicalRecords(arg0);
            return result;
        }
    }
    async getPatient(arg0: string): Promise<Patient | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatient(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatient(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatients(): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatients();
            return result;
        }
    }
    async getPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayments();
            return result;
        }
    }
    async getReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviews();
            return result;
        }
    }
    async getTodayAppointments(arg0: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayAppointments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayAppointments(arg0);
            return result;
        }
    }
    async updateAppointmentStatus(arg0: string, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointmentStatus(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointmentStatus(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateClinicInfo(arg0: Clinic): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClinicInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClinicInfo(arg0);
            return result;
        }
    }
    async updateCoupon(arg0: Coupon): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCoupon(arg0);
            return result;
        }
    }
    async updateDoctor(arg0: Doctor): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDoctor(arg0);
            return result;
        }
    }
    async updatePatient(arg0: Patient): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatient(arg0);
            return result;
        }
    }
    async updatePaymentStatus(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, arg1);
            return result;
        }
    }
    async validateCoupon(arg0: string): Promise<Coupon | null> {
        if (this.processError) {
            try {
                const result = await this.actor.validateCoupon(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateCoupon(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Clinic]): Clinic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Patient]): Patient | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Coupon]): Coupon | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
